call mvn install:install-file -Dfile=libs/kalkancrypt-0.6.1.jar -DgroupId=kz.gov.pki.kalkan -DartifactId=knca_provider_jce_kalkan -Dversion=0.6.1 -Dpackaging=jar
call mvn install:install-file -Dfile=libs/kalkancrypt_xmldsig-0.3.jar -DgroupId=kz.gov.pki.kalkan -DartifactId=kalkancrypt_xmldsig -Dversion=0.3 -Dpackaging=jar
call mvn install:install-file -Dfile=libs/xmlsec-1.5.8.jar -DgroupId=kz.gov.pki.kalkan -DartifactId=xmldsig -Dversion=0.3 -Dpackaging=jar
call mvn install:install-file -Dfile=libs/jsr105-1.0.jar -DgroupId=kz.gov.pki.kalkan -DartifactId=jsr105 -Dversion=1.0 -Dpackaging=jar
call mvn install:install-file -Dfile=libs/jtapi.jar -DgroupId=com.cisco -DartifactId=jtapi -Dversion=11.5 -Dpackaging=jar
call mvn install:install-file -Dfile=libs/ojdbc7.jar -DgroupId=com.oracle -DartifactId=ojdbc7 -Dversion=12.1.0 -Dpackaging=jar
call mvn install:install-file -Dfile=libs/TimesNewRomanKZ.jar -DgroupId=net.sf.jasperreports -DartifactId=TimesNewRomanKZ -Dversion=1.0.0 -Dpackaging=jar
call mvn install:install-file -Dfile=libs/knca_applet.jar -DgroupId=kz.fintech.knca_applet -DartifactId=knca_applet -Dversion=0.0.1 -Dpackaging=jar
call mvn install:install-file -Dfile=libs/crypto.gammaprov.jar -DgroupId=kz.gamma.jce -DartifactId=provider -Dversion=1.0.0 -Dpackaging=jar
call mvn install:install-file -Dfile=libs/jave-1.0.2.jar -DgroupId=it.sauronsoftware -DartifactId=jave -Dversion=1.0.2 -Dpackaging=jar
